name: Increase App Version
description: Increment the app version in app.json file (single app only).

inputs:
  Build_StagingDirectory:
    description: Path to the staging directory where app.json is located.
    required: true

runs:
  using: "composite"
  steps:
    - name: Increment App Version
      shell: pwsh
      run: |
        function Update-AppJsonVersion {
            param (
                [string]$AppJsonPath
            )

            if (Test-Path $AppJsonPath) {
                $app = Get-Content $AppJsonPath -Encoding UTF8 | ConvertFrom-Json
                $existingVersion = $app.version -as [version]
                $versionBuild = Get-Date -Format "yyyyMMdd"
                $versionRevision = Get-Date -Format "HHmmss"
                $nextVersion = [version]::new($existingVersion.Major, $existingVersion.Minor, $versionBuild, $versionRevision)
                $app.version = "$nextVersion"

                $app | ConvertTo-Json -Depth 100 | Set-Content $AppJsonPath -Encoding UTF8
                Write-Host "✅ Updated version in $AppJsonPath to $nextVersion"
            }
            else {
                Write-Error "❌ app.json not found at: $AppJsonPath"
                exit 1
            }
        }

        $RepoDir = Get-Location
        $mainAppPath = Join-Path $RepoDir "app.json"
        Update-AppJsonVersion $mainAppPath
