name: Increase App Version

description: Increment the app version in app.json files (main and test apps).

inputs:
  MAIN_APP_PATH:
    description: Path to the main app folder containing app.json.
    required: true
  TEST_APP_PATH:
    description: Path to the test app folder containing app.json.
    required: true
  Build_StagingDirectory:
    description: Path to the build staging directory.
    required: true
  IncrementType:
    description: Version increment type (e.g., patch, minor, major)
    required: false
    default: patch

runs:
  using: "composite"
  steps:
    - name: Increment Main and Test App Versions
      shell: pwsh
      run: |
        function Update-AppJsonVersion {
            param (
                [string]$AppJsonPath
            )

            if (Test-Path $AppJsonPath) {
                $app = Get-Content $AppJsonPath -Encoding UTF8 | ConvertFrom-Json
                $existingVersion = $app.version -as [version]
                $versionBuild = Get-Date -Format "yyyyMMdd"
                $versionRevision = Get-Date -Format "HHmmss"
                $nextVersion = [version]::new($existingVersion.Major, $existingVersion.Minor, $versionBuild, $versionRevision)
                $app.version = "$nextVersion"

                $app | ConvertTo-Json -Depth 100 | Set-Content $AppJsonPath -Encoding UTF8
                Write-Host "✅ Updated version in $AppJsonPath to $nextVersion"
            }
            else {
                Write-Error "❌ app.json not found at: $AppJsonPath"
                exit 1
            }
        }

        $RepoDir = Get-Location
        $mainAppJson = Join-Path $RepoDir "${{ inputs.MAIN_APP_PATH }}" | Join-Path -ChildPath "app.json"
        $testAppJson = Join-Path $RepoDir "${{ inputs.TEST_APP_PATH }}" | Join-Path -ChildPath "app.json"

        Update-AppJsonVersion -AppJsonPath $mainAppJson
        Update-AppJsonVersion -AppJsonPath $testAppJson
